# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
  desc "deploy to firebase"
  lane :firebase_deploy do
      sh "flutter clean"
      sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"
      release = firebase_app_distribution(
          app: "1:307455058391:android:cf87da1992b043eaf76b92",
          release_notes: "3ash yasta ! pease XD",
          firebase_cli_token: "1//03d268hiHqZa_CgYIARAAGAMSNwF-L9IrKbeDpiDtQgP74_ckzwzSyrMVs6nxV8WbZAgolOIinPs82HUri8zculXtKWvRdv5QtdM",
          android_artifact_type: "APK",
          android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
          
      )
  end
end
